/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3f465c",
        "surface-tint": "#565e74",
        "on-surface-variant": "#45464d",
        "secondary-fixed-dim": "#b4c5ff",
        "surface-variant": "#d3e4fe",
        "primary": "#000000",
        "surface-container": "#e5eeff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#003ea8",
        "on-background": "#0b1c30",
        "primary-fixed": "#dae2fd",
        "surface-container-high": "#dce9ff",
        "surface-dim": "#cbdbf5",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#bec6e0",
        "inverse-primary": "#bec6e0",
        "on-secondary-container": "#fefcff",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "inverse-surface": "#213145",
        "outline": "#76777d",
        "surface": "#f8f9ff",
        "tertiary-fixed": "#eaddff",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed-variant": "#5a00c6",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#9863ff",
        "on-tertiary-fixed": "#25005a",
        "surface-bright": "#f8f9ff",
        "secondary": "#0051d5",
        "primary-container": "#131b2e",
        "tertiary-container": "#25005a",
        "on-secondary-fixed": "#00174b",
        "on-surface": "#0b1c30",
        "on-error-container": "#93000a",
        "tertiary": "#000000",
        "outline-variant": "#c6c6cd",
        "secondary-fixed": "#dbe1ff",
        "surface-container-low": "#eff4ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#d2bbff",
        "on-primary-container": "#7c839b",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#316bf3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "margin-desktop": "3rem",
        "margin": "2rem",
        "space-xs": "0.25rem",
        "gutter-lg": "2rem",
        "gutter-sm": "1rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "code-tracking": ["JetBrains Mono", "monospace"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "code-tracking": ["13px", { lineHeight: "18px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}