server:
  port: 8080

spring:
    datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/grievance_db}
    username: ${DB_USERNAME:postgres}
    # The part after the colon is the fallback. It is safe to commit.
    password: ${DB_PASSWORD:postgres} 
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates/updates tables based on your Entities
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:VGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzMTIzNDU2Nzg5MA==}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}